#!/bin/bash
# Stage 04: Deliver
#
# PR mode  (PR_MODE=true):  push changes to the existing PR branch, comment on the PR,
#                           update labels on the PR.
# Issue mode (PR_MODE=false): commit, push a new branch, open a PR, update issue labels.
set -euo pipefail

cd "$REPO_DIR"

BLUEPRINT="$REPO_DIR/BLUEPRINT.md"
BASE_BRANCH="${BASE_BRANCH:-develop}"
PR_MODE="${PR_MODE:-false}"
PR_NUM="${PR_NUM:-}"

echo "=== Delivering (PR mode: $PR_MODE) ==="

# Configure git author for agent commits
git config user.email "loop-engineer[bot]@disciple.tools"
git config user.name  "DT Loop Engineer"

# Stage all changes (excluding loop artifacts)
git add --all
git reset HEAD -- BLUEPRINT.md QUESTIONS.md PROGRESS.md VERIFY_ERRORS.md 2>/dev/null || true

STAGED=$(git diff --cached --name-only)
if [[ -z "$STAGED" ]]; then
    echo "No changes to commit."
    # In PR mode this might be fine (agent confirmed it was already correct)
    # In issue mode it's a real error
    [[ "$PR_MODE" == "false" ]] && exit 1
fi

if [[ -n "$STAGED" ]]; then
    echo "Committing:"
    echo "$STAGED"
    git commit -m "fix(#${ISSUE_NUM}): ${ISSUE_TITLE}

Automated implementation by DT Loop Engineer.
Closes #${ISSUE_NUM}

Co-authored-by: loop-engineer[bot] <loop-engineer[bot]@disciple.tools>"
fi

BLUEPRINT_CONTENT=""
if [[ -f "$BLUEPRINT" ]]; then
    BLUEPRINT_CONTENT=$(cat "$BLUEPRINT")
fi

VERIFY_SUMMARY="All automated checks passed:
- PHP syntax & PHPCS
- PHPUnit (multisite)
- Browser E2E (Playwright MCP)"

if [[ "$PR_MODE" == "true" ]]; then
    # ── PR mode: update the existing PR ─────────────────────────────────────
    git push origin "$AGENT_BRANCH"

    gh pr comment "$PR_NUM" \
        --repo "$GITHUB_OWNER/$TARGET_REPO" \
        --body "**Agent completed work.** All verification checks passed — ready for review.

$VERIFY_SUMMARY"

    # Remove working labels, apply ready label — all on the PR
    gh pr edit "$PR_NUM" \
        --repo "$GITHUB_OWNER/$TARGET_REPO" \
        --remove-label "$PROCESSING_LABEL" \
        --add-label "$READY_LABEL" \
        2>/dev/null || true
    gh pr edit "$PR_NUM" \
        --repo "$GITHUB_OWNER/$TARGET_REPO" \
        --remove-label "$TRIGGER_LABEL" \
        2>/dev/null || true

    echo "PR #$PR_NUM updated. Done."

else
    # ── Issue mode: push branch and open a new PR ────────────────────────────
    git push origin "$AGENT_BRANCH"

    PR_URL=$(gh pr create \
        --repo "$GITHUB_OWNER/$TARGET_REPO" \
        --base "$BASE_BRANCH" \
        --head "$AGENT_BRANCH" \
        --title "[Agent] $ISSUE_TITLE" \
        --body "$(cat <<EOF
## Summary

Closes #${ISSUE_NUM}

This PR was generated by the DT Loop Engineer autonomous agent.

---

## Blueprint

${BLUEPRINT_CONTENT}

---

## Verification

${VERIFY_SUMMARY}

_Review the changes above and merge when satisfied._
EOF
)")

    echo "PR opened: $PR_URL"

    # Update labels on the original issue
    gh issue edit "$ISSUE_NUM" \
        --repo "$GITHUB_OWNER/$TARGET_REPO" \
        --remove-label "$PROCESSING_LABEL" \
        --add-label "$READY_LABEL" \
        2>/dev/null || true
    gh issue edit "$ISSUE_NUM" \
        --repo "$GITHUB_OWNER/$TARGET_REPO" \
        --remove-label "$TRIGGER_LABEL" \
        2>/dev/null || true

    # Link PR back to the issue
    gh issue comment "$ISSUE_NUM" \
        --repo "$GITHUB_OWNER/$TARGET_REPO" \
        --body "**Agent completed work.** PR ready for review: $PR_URL"

    echo "Issue #${ISSUE_NUM} updated. Done."
fi
