#!/bin/bash
# Stage 04: Deliver — commit changes, push branch, open PR, update issue labels.
set -euo pipefail

cd "$REPO_DIR"

BLUEPRINT="$REPO_DIR/BLUEPRINT.md"
BASE_BRANCH="${BASE_BRANCH:-develop}"

echo "=== Delivering PR ==="

# Configure git author for agent commits
git config user.email "loop-engineer[bot]@disciple.tools"
git config user.name  "DT Loop Engineer"

# Stage all changes (excluding loop artifacts)
git add --all
git reset HEAD -- BLUEPRINT.md PROGRESS.md VERIFY_ERRORS.md 2>/dev/null || true

STAGED=$(git diff --cached --name-only)
if [[ -z "$STAGED" ]]; then
    echo "No changes to commit."
    exit 1
fi

echo "Committing:"
echo "$STAGED"

git commit -m "fix(#${ISSUE_NUM}): ${ISSUE_TITLE}

Automated implementation by DT Loop Engineer.
Closes #${ISSUE_NUM}

Co-authored-by: loop-engineer[bot] <loop-engineer[bot]@disciple.tools>"

# Push the agent branch
git push origin "$AGENT_BRANCH"

# Build PR body from blueprint summary
BLUEPRINT_CONTENT=""
if [[ -f "$BLUEPRINT" ]]; then
    BLUEPRINT_CONTENT=$(cat "$BLUEPRINT")
fi

PR_URL=$(gh pr create \
    --repo "$GITHUB_OWNER/$TARGET_REPO" \
    --base "$BASE_BRANCH" \
    --head "$AGENT_BRANCH" \
    --title "[Agent] $ISSUE_TITLE" \
    --body "$(cat <<EOF
## Summary

Closes #${ISSUE_NUM}

This PR was generated by the DT Loop Engineer autonomous agent.

---

## Blueprint

${BLUEPRINT_CONTENT}

---

## Verification

All automated checks passed:
- PHP syntax & PHPCS
- PHPUnit (multisite)
- Browser E2E (Playwright MCP)

_Review the changes above and merge when satisfied._
EOF
)")

echo "PR opened: $PR_URL"

# Update issue labels
gh issue edit "$ISSUE_NUM" \
    --repo "$GITHUB_OWNER/$TARGET_REPO" \
    --remove-label "$TRIGGER_LABEL" \
    --add-label "$READY_LABEL"

# Link PR in issue comment
gh issue comment "$ISSUE_NUM" \
    --repo "$GITHUB_OWNER/$TARGET_REPO" \
    --body "**Agent completed work.** PR ready for review: $PR_URL"

echo "Issue #${ISSUE_NUM} updated. Done."
